version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: data_postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data
    ports:
      - "55432:5432"